site_name: Motorica Studio Documentation
theme:
  name: material
  palette:
    primary: custom
  features:
    - navigation.footer
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
        permalink: "🔗&#xFE0E;"
