site_name: Motorica Studio Documentation
theme:
  name: material
  custom_dir: overrides
  palette:
    primary: custom
  features:
    - navigation.footer
extra:
  analytics:
    provider: google
    property: G-6T46ZH1VJ9
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://forms.gle/7RzNWNHxDxTzm4FH8" target="_blank" rel="noopener">feedback form</a>.
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - awesome-pages
  - mkdocs-video
  - redirects:
      redirect_maps:
        "manual/unreal-engine/index.md": "index.md"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: "🔗&#xFE0E;"
      toc_depth: 3
